---
#file: playbook.yml
# Written By: Saed Alavinia (saedalav@gmail.com)

  - hosts: all
    remote_user: vagrant
    become: true
    become_method: sudo

    # Variable Section
    vars: 
      #{{HOST_SYNCED_LOCATION}}
      #{{VM_SYNCED_LOCATION}}
      script_host_location: {{HOST_SYNCED_FOLDER}}/scripts/printIP.py
      script_vm_location: /opt/pythonscripts/
   


    # --- Task Section ---
    tasks: 
    - name: Update apt cache                      # Updating apt cache
      apt: update_cache=yes                   
     
    - name: Install Apache                        # Install Apache2 
      apt: name=apache2 state=latest              # Keeps it at the latest version
     
    - name: enabled mod_rewrite                   # Enables rewrite module
      apache2_module: name=rewrite state=present
      notify:                                     # Restart Apache if changed=true
        - restart Apache2

    - name: create a directory in /opt            #
      file: state="directory" dest="{{script_vm_location}}/" mode="u=rwx" owner="vagrant"


    - name: copy python script to the vagrantServer
      copy: src="script_host_location" dest="{{script_vm_location" 


    # --- Handlers Section ---
    handlers: 
    - name: restart Apache2
      service: name=apache2 state=restarted