---
#file: playbook.yml
# Written By: Saed Alavinia (saedalav@gmail.com)

# This playbook is executed from a vagrantfile. A few variables
# are passed from vagrant to this playbook. (See comments in variable section)
# they are not used, but are very helpful if synced folder are being used

# On execution: 
# 1. Updates apt cache to make sure the latest is available
# 2. Installs apache2
# 3. Enables mod_rewrite for apache 
# 4. Creates a directory so that a prepared python script can be copied to 
# 5. Copies the python script from host to vagrant 
# 6. executes the python script
#    Python script check http://checkip.dyndns.org and prints the output (an IP address)
#    along with the timestamp into a file

#An added part of the solution now creates a new folder in /var/www/html/ 
#To change the index.html for apache

  - hosts: all
    remote_user: vagrant
    become: true
    become_method: sudo

    # Variable Section
    vars: 
      #PASSED FROM VAGRANTFILE: {{HOST_SYNCED_FOLDER}}
      #PASSED FROM VAGRANTFILE  {{VM_SYNCED_FOLDER}}
      script_host_location: scripts/              #relative address where python scrip is available
      script_vm_location: /opt/pythonscripts/     #location on vagrant vm where the script gets copied
      script_name: printIP.py                     #name of the python script
    

      #apache virtual host config
      http_root_doc: /var/www/html/newroot
      apache2_virtual_conf_location: /etc/apache2/sites-enabled/000-default.conf
      template_name : virtualhost.conf
      http_port: 80
      server_admin: saedalav@gmail.com

    # --- Task Section ---
    tasks: 
   
    - name: Update apt cache                      # Updating apt cache
      apt: update_cache=yes                   
     
    - name: Install Apache                        # Install Apache2 
      apt: name=apache2 state=latest              # Keeps it at the latest version
     
    - name: Enable mod_rewrite                   # Enables rewrite module
      apache2_module: name=rewrite state=present
      notify:                                     # Restart Apache if changed=true
        - restart Apache2

    - name: Create a directory to which script gets copied  #creates a folder to preserve mode
      file: state="directory" dest="{{script_vm_location}}/" mode="u=rwx" owner="vagrant"

    - name: Copy python script from host to vagrant #copies python to vagrant
      copy: src="{{script_host_location}}/{{script_name}}" dest="{{script_vm_location}}" 

    #Part of the branched solution. Creating a new folder to act as the new document root
    - name: create a directory in /var/www/html for our new index.html
      file: state="directory" dest="{{http_root_doc}}" mode="u=rwx" owner="vagrant"

    - name: Execute python script #runs python script 
      command: python "{{script_vm_location}}/{{script_name}}"


    #creates a new virtual host file for apache from apache template
    - name: create virtual host file
      template: src="{{template_name}}" dest="{{apache2_virtual_conf_location}}"
      notify: 
        - restart apache
     
    #Attempting to find the IP address to make testing easier
    - name: Finding IP Address
      set_fact:
        public_ip: "{{ item }}"
      with_items: "{{ansible_all_ipv4_addresses}}"
      when: "item.startswith('192.168.')"

      #Printing IP address to screen 
    - name: Print IP Address 
      debug: msg="Place {{public_ip}} in a browser to view an HTML version of the output"



    # --- Handlers Section ---
    handlers: 
    - name: restart Apache2
      service: name=apache2 state=restarted